"""Alert domain models for the analytics engine.

AlertType: categories of market alerts (foreign acceleration, basis divergence, etc.)
AlertSeverity: urgency levels (info, warning, critical)
Alert: single alert instance with dedup-friendly fields
"""

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class AlertType(str, Enum):
    FOREIGN_ACCELERATION = "foreign_acceleration"
    BASIS_DIVERGENCE = "basis_divergence"
    VOLUME_SPIKE = "volume_spike"
    PRICE_BREAKOUT = "price_breakout"


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(BaseModel):
    """Single alert instance generated by the analytics engine."""

    id: str = Field(default_factory=lambda: uuid4().hex[:8])
    alert_type: AlertType
    severity: AlertSeverity
    symbol: str
    message: str
    timestamp: datetime = Field(default_factory=datetime.now)
    data: dict[str, Any] = {}  # arbitrary context payload
